### ISSUE TITLE
Relationship with broom::augment?

### ISSUE THREAD

**Issue by hughjonesd** [leeper/prediction#20]
This looks interesting. Could I ask how it relates to `broom::augment`?

**Comment by leeper** [comment]
They're similar. This one solves a narrower problem (namely getting predicted values in a data frame). It exists primarily to support the margins package.

 broom does more than that. They also take slightly different approaches in handling predictions.

**Comment by hughjonesd** [comment]
Do you think it would it be worthwhile to merge some of the package into
broom::augment?
