### ISSUE TITLE
prediction package not found

### ISSUE THREAD

**Issue by camppdx** [leeper/prediction#42]
Please specify whether your issue is about:

 - [X] a possible bug
 - [X] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 I'm trying to simply download and apply the 'margins' package, however I keep getting this error issue related to not finding 'prediction'. I'm using R studio, R version 3.4.4. Do you have suggestions to remedy this? 

```R
install.packages("margins")
```
Warning in install.packages :
  dependency ‘prediction’ is not available
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/margins_0.3.23.zip'
Content type 'application/zip' length 1906146 bytes (1.8 MB)
downloaded 1.8 MB
package ‘margins’ successfully unpacked and MD5 sums checked

```R
## load package
library("margins")
```
package �margins� was built under R version 3.4.4
 
 Traceback
Error: package or namespace load failed for ‘margins’ in loadNamespace(j <- i[[1L]], c(lib.loc,.libPaths()), versionCheck = vI[[j]]): there is no package called ‘prediction’
6. stop(msg, call. = FALSE, domain = NA)
5. value[[3L]](cond)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
3. tryCatchList(expr, classes, parentenv, handlers)
2. tryCatch({ attr(package, "LibPath") <- which.lib.loc ns <- loadNamespace(package, lib.loc) env <- attachNamespace(ns, pos = pos, deps) ...
1. library(margins)

**Comment by leeper** [comment]
Can you try again? This sounds like a flaky error, as the package is definitely on CRAN.

**Comment by camppdx** [comment]
Thanks for the reply. It looks like you're right, it was a flaky issue. I
updated all of my R files to the most recent version and it seems to find
the 'prediction' package now.

Thanks!
