### ISSUE TITLE
Add support for ridge::linearRidge prediction

### ISSUE THREAD

**Issue by dfrankow** [leeper/prediction#44]
I'm trying to get margins for ridge regression. To do that, I need the predictions package to support ridge::linearRidge. I have a PR I'll send for review.

**Comment by dfrankow** [comment]
Here's the pull request: https://github.com/leeper/prediction/pull/45/files

**Comment by leeper** [comment]
thanks!

**Comment by dfrankow** [comment]
You're welcome.

However, I concluded I won't be able to make progress on margins for ridge. See https://github.com/leeper/margins/issues/140#issuecomment-627541489.

I hope this change is still helpful in some way.
