### ISSUE TITLE
merge with broom?

### ISSUE THREAD

**Issue by bbolker** [leeper/prediction#6]
Radical thought, but would you consider/what would you think about merging this functionality with the `broom` package?  It feels like it would be easier to have a smaller number of packages for dealing with tidy model outputs ...

**Comment by leeper** [comment]
I'm amenable to that. This is code that was refactored out of [margins](https://github.com/leeper/margins) for maintainability. My impression is broom doesn't implement a predicted/fitted values for particularly large range of model classes does it? (I haven't used it much, so I don't really know.)

**Comment by bbolker** [comment]
(FWIW I haven't even asked the broom maintainer about this yet.)  This might nicely augment the current 'verbs' in broom, which are `tidy` (coefficient table), `augment` (original data + residuals, predictions, etc. -> update of old `ggplot2::fortify`) and `glance` (model summaries such as AIC, R2, etc.).  `augment` is really designed around the *original* data (although e.g. `augment.lm` does take a `newdata` argument ...)

**Comment by leeper** [comment]
Ah, okay. For this, being able to pass new data is kind of essential. I'll take a more thorough look at broom at some point and see how this might all fit together.
